spring.application.name=SpringAiProject
spring.ai.openai.api-key=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
